image: ruby:2.3

pages:
  stage: deploy
  script:
  - apt-get update -y
  - apt-get install -y locales imagemagick
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export LC_CTYPE=en_US.UTF-8
  - gem install bundler -v 2.3.26
  - bundle install
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
