image: ruby:2.3

test:
  stage: test
  script:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export LC_CTYPE=en_US.UTF-8
  - gem install bundler
  - bundle install
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export LC_CTYPE=en_US.UTF-8
  - gem install bundler
  - bundle install
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
