---
title: Run Loch Lomond 10K
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Enter the Run Loch Lomond 10K.

'
baseurl: ''
url: "/"
plugins:
- bootstrap
- autoprefixer-rails
- jekyll-assets
markdown: kramdown
exclude:
- vendor
- tags
- tags.temp
- tags.lock
- README.md
assets:
  autoprefixer:
    browsers:
    - last 2 versions
    - IE > 9
  prefix: "/assets"
  digest: true
  compress:
    css: true
    js: true
  assets:
  - app.scss
  - app.js
  - "*.png"
  - "*.jpeg"
  - "*.svg"
  - "*.jpg"
  - "*.gif"
  sources:
  - _assets/css
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets
  - _assets/fonts
  - _assets/img
  - _assets/js
  - images/
  features:
    automatic_img_size: true
    automatic_img_alt: true
