---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
collections: 
upload_dir: images
public_path: "{{ site.baseurl }}/images"
front_matter_path: "/images"
use_front_matter_path: true
file_template: ":filename:"
