---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: none
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: images
public_path: "{{ site.baseurl }}/images"
front_matter_path: "/images"
use_front_matter_path: true
file_template: ":filename:"
